### ISSUE TITLE
Menu do site não fecha em resoluções menores do que 768px

### ISSUE THREAD

**Issue by teles** [transparenciasjc/repasse-server#108]
Problema: Em resoluções menores do que 768px o site fica com menu tipo mobile, mas o menu não fecha. 
Solução: Criar um botão de abrir/fechar para o site em resoluções menores do que 768px.

**Comment by teles** [comment]
Estou abrindo as issues, @jesuino

**Comment by jesuino** [comment]
Muito obrigado <3
