### ISSUE TITLE
acessar a API por outras plataformas

### ISSUE THREAD

**Issue by quicoli** [transparenciasjc/repasse-server#179]
Parabéns pelo projeto. Estou com uma dúvida quanto ao acesso à API. Essa API não possui um endereço público? Só consigo acessar se for através do client javascript? Quero fazer um APP android/ios/windows mas não enxerguei como acessar essa API....

**Comment by jesuino** [comment]
Olá,

Todos os endpoints da API estão disponíveis em: http://repasse.ufabc.edu.br/desenvolvedores.html.

O endpoint público é: http://repasse.ufabc.edu.br/rest

Um exemplo: http://repasse.ufabc.edu.br/rest/ranking/2015/SP/SAO%20JOSE%20DOS%20CAMPOS

Tudo é em JSON.

Infelizmente algo quebrou o plugin do RAML e tive que deixar a página padrão que usa um host fake, por isso o API explorer não está funcionando! 

Pode consumir diretamente de uma APP, por enquanto não temos API Key e provavelmente em breve teremos um Servlet Filter pra contar os acessos à API. Se ficar muito pensado faremos Key, mas por enquanto tá suava :) 

Há mais alguma dúvida ou posso fechar?

**Comment by quicoli** [comment]
William,

muito obrigado pelas explicações. Fiz um teste aqui, o endpoint público
está funcionando, valeu!

Pode fechar o ticket.

Abraço

Em 25 de setembro de 2016 19:52, William Antônio Siqueira <
notifications@github.com> escreveu:

**Comment by jesuino** [comment]
Obrigado Ç)
