### ISSUE TITLE
O que acham de mudar o client de angular js para angular 2?

### ISSUE THREAD

**Issue by emerson-diego** [transparenciasjc/repasse-server#189]
Tenho conhecimento de angular 2 e posso contribuir...

**Comment by jesuino** [comment]
Olá Emerson,

É um tópico pertinente. Antes precisamos migrar o cliente para repasse-cliente, então vou deixar o issue aberto para voltar a esse tópico depois!

**Comment by jesuino** [comment]
Olá Emerson,

No momento decidimos manter o cliente com angular 1 e futuramente iremos modificar todo o cliente.

Caso queria contribuir com angular 1 ou qualquer outra coisa fique a vontade!
