### ISSUE TITLE
Colocar valores monetários no formato R$ 000.000,00

### ISSUE THREAD

**Issue by giovaneliberato** [transparenciasjc/repasse-server#60]
Hoje, os valores são exibidos como R$ 535754.63, o que dificulta a leitura.
Sugiro a formatação R$ 000.000,00

**Comment by jesuino** [comment]
Eu concordo plenamente, tenho que aprender a formatar com a API do Highcharts de acordo com o locale to usuário!

**Comment by PauloLuan** [comment]
Fiz algo parecido aqui: https://github.com/transparenciasjc/salarios/blob/gh-pages/index.html#L35

**Comment by giovaneliberato** [comment]
<3

**Comment by jesuino** [comment]
<3

**Comment by PauloLuan** [comment]
<3
