### ISSUE TITLE
Usar um AutoComplete ao invés de Combobox

### ISSUE THREAD

**Issue by PauloLuan** [transparenciasjc/repasse-server#91]
Na pesquisa das Cidades  / Estados poderíamos ter só o combo dos municípios de forma o usuário procurar rapidamente sua cidade (odeio aquele combobox estático sem pesquisa)

Adicionalmente, poderia adicionar uma pesquisa naquele combobox caso não queria mudar o workflow de como as coisas são feitas.

Exemplo: http://ghiden.github.io/angucomplete-alt/#example1

**Comment by jesuino** [comment]
Isso foi pedido aqui por um usuário: #20 

Depois ele voltou atrás, mas agora que há um novo pedido vou fazer, mas irei usar o JQuery UI, pois já foi carregado:

https://jqueryui.com/autocomplete/#combobox

**Comment by jesuino** [comment]
Criei um auto complete mais ou menos no explorar, tem que melhorar, mas vou fechar o issue por enquanto
