### ISSUE TITLE
Porque as variáveis estão em português?

### ISSUE THREAD

**Issue by PauloLuan** [transparenciasjc/repasse-server#93]
Tenho TOC com código em BR, pode ser chatisse minha, mas acho que fica mais legal quando as variáveis são em inglês.

**Comment by pedro-hos** [comment]
Acho que tem que ser em português mesmo, assim mais pessoas podem ajudar!

**Comment by jesuino** [comment]
Eu concordo plenamente! Parece estranho de primeira, mas depois a gente acostuma.

**Comment by PauloLuan** [comment]
Sou contra, e sempre serei. Só digo isso: "Linguagens de Programação, linguagens de script, comandos de sistema operacional, etc, são todos baseados na língua Inglesa. Então, por que você faria diferente no seu código?"

http://www.akitaonrails.com/2008/07/31/tradu-o-por-que-voc-n-o-deve-codificar-em-portugu-s

**Comment by PauloLuan** [comment]
http://pt.stackoverflow.com/questions/301/devo-escrever-meu-programa-em-ingl%C3%AAs-ou-portugu%C3%AAs

**Comment by jesuino** [comment]
hehehe posso te garantir que já li todos os argumentos a favor de variáveis em PT X EN; Quando a gente tiver uma versão completa beta (1.0 Beta) dá pra fazer o rewrite. Por mim tanto faz, não colocando nomes enigmáticos de variáveis (a, b, c pq, xi, etc), tanto faz.

**Comment by jesuino** [comment]
Elas vão fcar em PT. em brve vai rolar o handover do projeto e a pessoal que vai vir pode não saber inglês - mas nesse ponto seria ruim fazer o refactor!
